[package]
name = "wolfsbane"
version = "0.1.0"
authors = ["MT"]
edition = "2018"

[dependencies]
glium = "*"
straal = { git = "https://github.com/mtesseracttech/straal", branch = "develop" }
vertexify = { git = "https://github.com/mtesseracttech/vertexify"}